#!/bin/bash

set -e

case `uname` in
	Linux)
	;;

	*)
		echo
		echo
		echo "You need to be running in your vagrant virtual machine to run this."
		echo
		echo "Run vagrant ssh from the root directory of the development environment and then re-run this script"
		echo
		exit 1
	;;
esac

/vagrant/script/bootstrap $@
