#!/bin/bash

# Uncomment next line to enable debug
#set -x

source script/dev/configure
apps=`cat script/utils/apps | grep -v \# | grep -v '^\s*$'`

rm -f ./Procfile

for app in ${apps}; do
	procfile="apps/${app}/Procfile"

	if [[ -f ${procfile} ]]
		then
			echo "Merging procfile for ${app}"
			echo "${app}: script/start ${app}" >> Procfile
		fi
done

foreman start
