#!/bin/bash

# Uncomment next line to enable debug
#set -x

source script/dev/configure

rm -f ./Procfile

for app in ${apps}; do
	procfile="apps/${app}/Procfile"

	if [[ -f ${procfile} ]]
		then
			echo "Merging procfile for ${app}"
			echo "${app}: script/start ${app}" >> Procfile
		fi
done

foreman start
