#!/bin/bash

# Uncomment next line to enable debug
#set -x

source script/dev/configure
apps_and_ports=`cat script/utils/apps | grep -v \# | grep -v '^\s*$'`

rm -f ./Procfile

for app_and_port in ${apps_and_ports}; do
	app=`echo ${app_and_port} | cut -d':' -f1`
    procfile="apps/${app}/Procfile"
	
	if [[ -f ${procfile} ]]
 	then
 		echo "Merging procfile for ${app}"
        app_name=$(echo $app |  sed 's/-//g' )
 		echo "${app_name}: script/start ${app}" >> Procfile
	fi
done

foreman start
