#!/bin/bash

if [[ -d .virtualenv ]]
	then
		echo "No virtual environment found in .virtualenv"
		echo "You probably need to run dev/run-app ./run.sh to create one"
		exit 1
	fi

source .virtualenv/bin/activate