#!/bin/bash


echo
echo "I am going to activate the virtual environment for ${app_name} in a new shell"
echo "To exit from this environment simply exit the shell (with 'exit' or CTRL-D)"
echo

source dev/configure

bash -e dev/venv -i