#!/bin/bash

#Uncomment this line if you want to debug this script
#set -x

source dev/configure
source dev/virtualenv-functions

if [[ -d tests ]] ; then
    create_virtual_env
    workon ${app_name}
    install_requirements
    install_test_requirements

    export SETTINGS="config.TestConfig"

    echo "Configuring SETTINGS to be config.TestConfig"
    echo "Please ensure you have a config.TestConfig in your project"

    # Thinking of doing this below it means all requirements_test.txt
    # need updating to have pytest-cov
    # and some of the modules need to be renamed to follow
    # github repo (app_name) == project-name and python module == projectname
    # if run-all-tests is to work
    module_name=$(echo $app_name |  sed 's/-//g' )
    py.test --cov ${module_name} tests/ --cov-report=term --cov-report=html

else
    echo "No unit tests found in ${app_name}"
fi
