#!/bin/bash

#Uncomment this line if you want to debug this script
#set -x

script_to_run=${@}

if [[ -z ${script_to_run} ]]
	then
		if [[ -f run.sh ]]
			then	
				echo "Defaulting to run.sh as startup script"
				script_to_run="run.sh"
		else
			echo "You haven't supplied a script to run and there is no run.sh in your project"
			echo "I don't know what you want me to start"
			exit 1
		fi
	fi

if [[ ! -f ${script_to_run} ]]
	then
		echo "I can't find the run script ${script_to_run}"
		echo "Normally you would run"
		echo "run-app ./<script-to-run>"
		exit 1
	fi


source /vagrant/script/dev/configure
source /vagrant/script/dev/virtualenv-functions

create_virtual_env
workon ${app_name}
install_requirements

. ${script_to_run}
