#!/bin/bash

#Uncomment this line if you want to debug this script
#set -x

source dev/configure
source dev/virtualenv-functions

if [[ -d tests ]] ; then
    create_virtual_env
    workon ${app_name}
    install_requirements
    install_test_requirements

    export SETTINGS="config.TestConfig"

    echo "Configuring SETTINGS to be config.TestConfig"
    echo "Please ensure you have a config.TestConfig in your project"
    
    py.test
else
    echo "No unit tests found in ${app_name}"
fi
