#!/bin/bash

#set -x
set -e
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh

export app_name=`basename ${PWD}` 

function install_requirements {
	if [[ -f ./requirements.txt ]] ; then
		pip install -r ./requirements.txt
	fi 

	if [[ -f ./requirements_test.txt ]] ; then
		pip install -r ./requirements_test.txt
	fi 
}

function create_virtual_env {
	if [[ ! -d ${WORKON_HOME}/${app_name} ]] ; then
		echo "Creating python virtual env for ${app_name} in ${WORKON_HOME}"
		set +o errexit
		mkvirtualenv -a ${PWD} -r /vagrant/script/dev/venv-requirements.txt ${app_name}
		set -e
	fi
	
	echo "Activating virtual envrionment [${app_name}]"
	set +o errexit
	workon ${app_name}
	set -e
	echo "Installing core requirements in virtual envrionment [${app_name}]"
	pip install -r /vagrant/script/dev/venv-requirements.txt
}

function remove_virtual_env {
	if [[ -d ${WORKON_HOME}/${app_name} ]] ; then
		echo "Removing python virtual env for ${app_name} in ${WORKON_HOME}"
		set +o errexit
		rmvirtualenv ${app_name}
		set -e
	fi
}

