#!/bin/bash

# Uncomment the line below if you want to run this script with debug turned on
set -x

source script/dev/configure
source script/utils/checkout
 
apps=`cat script/utils/apps | grep -v \# | grep -v '^\s*$'`

checkout ${apps}

for app in ${apps}; do
	app_dir=apps/${app}

	if [[ ! -d ${app_dir}/dev ]]
		then
			echo "Configuring developer scripts for ${app}"
			mkdir -p ${app_dir}/dev
			cp -r script/dev ${app_dir}
		fi
done

export WORKON_HOME