#!/bin/bash

# Uncomment the line below if you want to run this script with debug turned on
#set -x

source script/dev/configure
source script/checkout
 
apps_and_ports=`cat script/apps | grep -v \# | grep -v '^\s*$'`

for app_and_port in ${apps_and_ports}; do
	app=`echo ${app_and_port} | cut -d':' -f1`
	port=`echo ${app_and_port} | cut -d':' -f2`

	checkout ${app}
	app_dir=apps/${app}

	if [[ ! -d ${app_dir}/dev ]]
		then
			echo "Configuring developer scripts for ${app}"
			mkdir -p ${app_dir}/dev
			cp -r script/dev ${app_dir}
			echo ${port} > ${app_dir}/dev/port
		fi
done

export WORKON_HOME
