#!/bin/bash

function checkout {
  app=$1
 
  if [[ ! -d apps/${app} ]] ; then 
    mkdir -p apps/
    git -C apps/ clone git@github.com:landregistry/${app}.git

    if [[ -f apps/${app}/.gitmodules ]] ; then
      echo "Initialising git submodule for ${app}"
      git -C apps/${app} submodule init
      git -C apps/${app} submodule update
    fi
  fi
}

function update_app {
  app=$1
    
  if [ -d apps/${app} ] ; then
    echo "Refreshing application ${app}"
    cd apps/${app}
    git pull
    cd -

     if [[ -f apps/${app}/.gitmodules ]] ; then
      echo "Initialising git submodule for ${app}"
      git -C apps/${app} submodule init
      git -C apps/${app} submodule update
    fi
  fi
}