#!/bin/bash

set -e

source /vagrant/script/checkout	

if [[ -z ${@} ]] ; then
	echo "No application specified to start!" 
	exit 1
fi

set +o errexit
workon $@
cd /vagrant/apps/$@
PORT=$(get_port_for_app $1) source run.sh | tee -a /vagrant/logs/${@}.log 2>&1
deactivate
set -e
