#!/bin/bash

set -e

source /vagrant/script/dev-env-functions

if [[ -z ${@} ]] ; then
	echo "No application specified to start!"
	exit 1
fi

set +o errexit
create_virtual_env $1 > >(tee -a /vagrant/logs/venv_setup_${1}.log) 2>&1
workon $1
source_app_environment $1
source_secrets
SETTINGS='config.DevelopmentConfig' PORT=$(get_port_for_app $1) . run.sh > >(tee -a /vagrant/logs/${1}.log) 2>&1
deactivate
set -e
