#!/bin/bash

set -e

source /vagrant/script/dev-env-functions

if [[ -z ${@} ]] ; then
	echo "No application specified to start!" 
	exit 1
fi

set +o errexit
workon $1
source_app_environment $1
SETTINGS='config.DevelopmentConfig' PORT=$(get_port_for_app $1) . run.sh 2> >(tee -a /vagrant/logs/${1}.log)
deactivate
set -e