#!/bin/bash

#set -x

if [[ ! -d apps ]] ; then
	./bootstrap
fi

source script/dev/configure
source script/checkout
 
apps_and_ports=`cat script/apps | grep -v \# | grep -v '^\s*$'`

for app_and_port in ${apps_and_ports}; do
	app=`echo ${app_and_port} | cut -d':' -f1`
	port=`echo ${app_and_port} | cut -d':' -f2`

	update_app ${app}
done